export const path = {
    MAIN: '/*',
    HOME: 'home',
    LOGIN: 'login',
    FORGET_PASSWORD: 'quen-mat-khau',

    RENTAL_ROOM: 'cho-thue-phong-tro',
    RENTAL_HOUSE: 'nha-cho-thue',
    RENTAL_APARTMENT: 'cho-thue-can-ho',
    RENTAL_SPACE: 'cho-thue-mat-bang',
    DETAIL_POST__POST_ID: `post/:postId`,
    LIKED_POST: 'tin-da-luu',

    SYSTEM: '/quan-ly',
    USER_MANAGEMENT: 'thong-tin-tai-khoan',
    TRANSACTION_MANAGEMENT: 'lich-su-giao-dich',
    TOP_UP: 'nap-tien',
    MOMO: 'momo',
    VNPAY: 'vnpay',
    STATUS: 'trang-thai',
    POST_MANAGEMENT: 'tin-dang',
    MESSENGER: `tin-nhan`,
    MESSENGER__USER_ID: `tin-nhan/:userId`,
    CREATE_NEW_POST: 'dang-tin-moi',
    CHANGE_PASSWORD: 'doi-mat-khau',
    CHECKOUT__POST_ID: `thanh-toan/:postId`,

    ADMIN: '/admin',
    ADMIN_LOGIN: '/admin-login',
    ADMIN_USER_MANAGEMENT: 'users',
    ADMIN_POST_MANAGEMENT: 'posts',
    ADMIN_TRANSACTION_MANAGEMENT: 'transactions',
};
