const actionTypes = {
    // Auth
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    SET_MSG: 'SET_MSG',
    VERIFY_TOKEN_FROM_FIREBASE_SUCCESS: 'VERIFY_TOKEN_FROM_FIREBASE_SUCCESS',
    VERIFY_TOKEN_FROM_FIREBASE_FAIL: 'VERIFY_TOKEN_FROM_FIREBASE_FAIL',

    // Posts

    // Property Data
    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICES: 'GET_PRICES',
    GET_ACREAGES: 'GET_ACREAGES',

    // User
    GET_CURRENT_USER: 'GET_CURRENT_USER',

    //Theme
    TOGGLE_THEME: 'TOGGLE_THEME',
};

export default actionTypes;
