const actionTypes = {
  // Auth
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",

  // Posts
  GET_ALL_POSTS: "GET_ALL_POSTS",
  GET_POSTS: "GET_POSTS",

  // Property Data
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRICES: "GET_PRICES",
  GET_ACREAGES: "GET_ACREAGES",

  // Location Data
  GET_ALL_DISTRICTS: "GET_ALL_DISTRICTS",
  GET_ALL_PROVINCES: "GET_ALL_PROVINCES",
  GET_DISTRICTS: "GET_DISTRICTS",
  GET_PROVINCES: "GET_PROVINCES",
};

export default actionTypes;
