const actionTypes = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",
  GET_ALL_POSTS: "GET_ALL_POSTS",
  GET_POSTS: "GET_POSTS",
  GET_CATEGORIES: "GET_CATEGORIES",
};

export default actionTypes;
